[package]
name = "foreign-types-macros"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[features]
std = []

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
